#!/usr/bin/env python3

import os
import re
import sys
import xml.etree.ElementTree as ET
from shutil import copyfile

source = sys.argv[1]

print("Importing %s" % source)

root = ET.parse(source).getroot()

time = root.find('{http://www.topografix.com/GPX/1/1}metadata/{http://www.topografix.com/GPX/1/1}time').text
name = root.find('{http://www.topografix.com/GPX/1/1}trk/{http://www.topografix.com/GPX/1/1}name').text

time = time[:10]
year = time[:4]
name = name.lower()
name = re.sub('[^0-9a-zA-Z]+', '-', name)

if not os.path.exists(year):
    os.mkdir(year)

copyfile(source, str(year) + "/" + time + "-" + name + ".gpx")
